/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * BussNow API
 * API cho hệ thống đặt vé xe
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * Vai trò người dùng
 */
export type RegisterDTORole = typeof RegisterDTORole[keyof typeof RegisterDTORole];


export const RegisterDTORole = {
  admin: 'admin',
  user: 'user',
  provider: 'provider',
  guest: 'guest',
} as const;

export interface RegisterDTO {
  /** Email đăng ký */
  email: string;
  /** Mật khẩu phải có ít nhất 1 chữ thường, 1 chữ hoa, 1 số, 1 ký tự đặc biệt và tối thiểu 8 ký tự */
  password: string;
  /** Họ và tên đệm */
  firstName: string;
  /** Tên */
  lastName: string;
  /** Số điện thoại (10 chữ số) */
  phoneNumber?: string;
  /** Địa chỉ */
  address?: string;
  /** Mã OTP xác thực */
  otp?: string;
  /** Vai trò người dùng */
  role: RegisterDTORole;
  /** Admin nội bộ tạo tài khoản */
  isInternalAdminCreate?: boolean;
}

export type CreateUserDtoRole = typeof CreateUserDtoRole[keyof typeof CreateUserDtoRole];


export const CreateUserDtoRole = {
  admin: 'admin',
  user: 'user',
  provider: 'provider',
  guest: 'guest',
} as const;

export interface CreateUserDto {
  avatar?: string;
  firstName: string;
  lastName: string;
  /** Ngày sinh hoặc ngày thành lập */
  birthDate?: string;
  address?: string;
  email: string;
  phoneNumber?: string;
  /** @minLength 6 */
  password: string;
  role?: CreateUserDtoRole;
}

export interface ChangePasswordDTO { [key: string]: unknown }

export interface UpdateProfileDTO {
  firstName?: string;
  lastName?: string;
  phoneNumber?: string;
  address?: string;
  birthDate?: string;
}

export interface CreateVehicleDTO { [key: string]: unknown }

export interface Vehicle { [key: string]: unknown }

export interface CreateRouteDTO {
  originId: string;
  destinationId: string;
  duration: number;
  restAtDestination: number;
  providerId?: string;
  stopPointIds: string[];
}

export interface CreateStopPointDto {
  name: string;
  address: string;
  cityId?: string;
}

export interface CreateLocationDto {
  locationName: string;
  stopPoints: CreateStopPointDto[];
}

export interface DeleteLocationDto {
  locationId: string;
}

export interface UpdateStopPointDto {
  stopPointId?: string;
  name: string;
  address: string;
}

export interface CreateTripDTO { [key: string]: unknown }

export interface GenTripDTO {
  vehicleId: string;
  startTime?: string;
  endTime: string;
  price: number;
}

export interface DeleteTripDTO { [key: string]: unknown }

export interface DeleteTripBeforeDate {
  date?: string;
}

/**
 * Phương thức thanh toán
 */
export type CreateTIcketDTOMethodPayment = typeof CreateTIcketDTOMethodPayment[keyof typeof CreateTIcketDTOMethodPayment];


export const CreateTIcketDTOMethodPayment = {
  BANKING: 'BANKING',
  CASH: 'CASH',
} as const;

/**
 * Trạng thái thanh toán
 */
export type CreateTIcketDTOStatusPayment = typeof CreateTIcketDTOStatusPayment[keyof typeof CreateTIcketDTOStatusPayment];


export const CreateTIcketDTOStatusPayment = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export interface CreateTIcketDTO {
  /** ID chuyến xe */
  tripId: string;
  /** Danh sách mã ghế */
  seatCode: number[];
  /** Phương thức thanh toán */
  methodPayment: CreateTIcketDTOMethodPayment;
  /** Trạng thái thanh toán */
  statusPayment?: CreateTIcketDTOStatusPayment;
  /** Tên khách (guest) */
  firstName?: string;
  /** Họ khách (guest) */
  lastName?: string;
  /** Số điện thoại khách */
  phone?: string;
  /** Email khách */
  email?: string;
}

export interface UpdateTicketDTO {
  ticketId: string;
  status: string;
}

export type SearchTicketDTOStatus = typeof SearchTicketDTOStatus[keyof typeof SearchTicketDTOStatus];


export const SearchTicketDTOStatus = {
  USED: 'USED',
  NOT_USED: 'NOT_USED',
} as const;

export type SearchTicketDTOStatusPayment = typeof SearchTicketDTOStatusPayment[keyof typeof SearchTicketDTOStatusPayment];


export const SearchTicketDTOStatusPayment = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
  CANCELLED: 'CANCELLED',
} as const;

export interface SearchTicketDTO {
  ticketId?: string;
  providerId?: string;
  providerPhone?: string;
  page?: number;
  limit?: number;
  phone?: string;
  status?: SearchTicketDTOStatus;
  vehicleId?: string;
  vehicleCode?: string;
  tripId?: string;
  statusPayment?: SearchTicketDTOStatusPayment;
}

export interface BankingInfoDTO {
  accountName: string;
  accountNumber: string;
  bankName: string;
}

export interface CancleTicketDTO {
  ticketId: string;
  bankingInfo?: BankingInfoDTO;
}

export interface ConfirmCancleTicketDTO {
  cancleTicketRequest: CancleTicketDTO;
  otp: string;
}

export interface FilterTicketDTO { [key: string]: unknown }

export type SearchRefundRequestDTOStatus = typeof SearchRefundRequestDTOStatus[keyof typeof SearchRefundRequestDTOStatus];


export const SearchRefundRequestDTOStatus = {
  PENDING: 'PENDING',
  COMPLETE: 'COMPLETE',
  REJECTED: 'REJECTED',
} as const;

export interface SearchRefundRequestDTO {
  page?: number;
  limit?: number;
  phoneNumber?: string;
  status?: SearchRefundRequestDTOStatus;
}

export interface UpdateCancellationRequestDto { [key: string]: unknown }

export interface CreatePaymentDto {
  /** Số tiền thanh toán (VND) */
  amount: number;
  /** Thông tin đơn hàng */
  orderInfo: string;
  bookingInfo: CreateTIcketDTO;
}

export interface CreateRequestDTO {
  companyName: string;
  address: string;
  phoneNumber: string;
  email: string;
  representativeName: string;
  licenseNumber: string;
  licenseFile?: string;
}

export type UpdateBusCompanyRequestDTOStatus = typeof UpdateBusCompanyRequestDTOStatus[keyof typeof UpdateBusCompanyRequestDTOStatus];


export const UpdateBusCompanyRequestDTOStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export interface UpdateBusCompanyRequestDTO {
  id: number;
  status: UpdateBusCompanyRequestDTOStatus;
  rejectReason?: string;
}

export type AuthControllerLoginParams = {
password: string;
email: string;
};

export type UserControllerSearchUserParams = {
userId?: string;
email?: string;
phone?: string;
page?: number;
limit?: number;
};

export type VehicleControllerGetVehiclesParams = {
/**
 * Lọc theo vehicleId cụ thể
 */
vehicleId?: string;
/**
 * Số lượng item/trang, mặc định 10
 */
limit?: number;
/**
 * Trang hiện tại, mặc định 1
 */
page?: number;
};

export type RouteControllerGetRoutesParams = {
/**
 * Số lượng item/trang, mặc định 10
 */
limit?: number;
/**
 * Trang hiện tại, mặc định 1
 */
page?: number;
};

export type StopPointControllerGetStopPointsParams = {
cityId?: string;
vehicleId?: string;
page?: number;
limit?: number;
};

export type TripControllerSearchTripParams = {
fromLocationId: string;
toLocationId: string;
departTime: string;
page: number;
limit: number;
busType?: string[];
minPrice?: number;
maxPrice?: number;
sortBy?: string;
};

export type TripControllerGetTripsByVehicleParams = {
/**
 * vehicleId
 */
vehicleId?: string;
page?: number;
limit?: number;
};

export type TicketControllerGetPaymentHistoryTicketParams = {
ticketId?: string;
};

export type TicketControllerGetMyTicketParams = {
ticketId?: string;
providerId?: string;
providerPhone?: string;
page?: number;
limit?: number;
phone?: string;
status?: TicketControllerGetMyTicketStatus;
vehicleId?: string;
vehicleCode?: string;
tripId?: string;
statusPayment?: TicketControllerGetMyTicketStatusPayment;
};

export type TicketControllerGetMyTicketStatus = typeof TicketControllerGetMyTicketStatus[keyof typeof TicketControllerGetMyTicketStatus];


export const TicketControllerGetMyTicketStatus = {
  USED: 'USED',
  NOT_USED: 'NOT_USED',
} as const;

export type TicketControllerGetMyTicketStatusPayment = typeof TicketControllerGetMyTicketStatusPayment[keyof typeof TicketControllerGetMyTicketStatusPayment];


export const TicketControllerGetMyTicketStatusPayment = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
  CANCELLED: 'CANCELLED',
} as const;

export type BusCompanyRequestControllerCreateBody = {
  companyName: string;
  address: string;
  phoneNumber: string;
  email: string;
  representativeName: string;
  licenseNumber: string;
  licenseFile?: Blob;
};

export type BusCompanyRequestControllerGetListParams = {
page?: number;
limit?: number;
requestId?: string;
phone?: string;
email?: string;
status?: BusCompanyRequestControllerGetListStatus;
fromDate?: string;
toDate?: string;
sortBy?: string;
};

export type BusCompanyRequestControllerGetListStatus = typeof BusCompanyRequestControllerGetListStatus[keyof typeof BusCompanyRequestControllerGetListStatus];


export const BusCompanyRequestControllerGetListStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const authControllerSendOtpRegister = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/send-otp-register`,undefined,options
    );
  }

export const authControllerRegister = <TData = AxiosResponse<void>>(
    registerDTO: RegisterDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/register`,
      registerDTO,options
    );
  }

export const authControllerRegisterProvider = <TData = AxiosResponse<void>>(
    createUserDto: CreateUserDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/register-provider`,
      createUserDto,options
    );
  }

export const authControllerLogin = <TData = AxiosResponse<void>>(
    params: AuthControllerLoginParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/auth/login`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const authControllerLogout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/logout`,undefined,options
    );
  }

export const authControllerSendOtp = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/send-otp`,undefined,options
    );
  }

export const authControllerVerifyOtp = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/verify-otp`,undefined,options
    );
  }

export const authControllerSendReserPasswordLink = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/send-reset-password-link`,undefined,options
    );
  }

export const authControllerResetPassword = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/reset-password`,undefined,options
    );
  }

export const authControllerChangePassword = <TData = AxiosResponse<void>>(
    changePasswordDTO: ChangePasswordDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/auth/changePassword`,
      changePasswordDTO,options
    );
  }

export const authControllerGoogleAuth = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/auth/google`,options
    );
  }

export const authControllerGoogleAuthCallback = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/auth/google/callback`,options
    );
  }

export const userControllerCreateGuest = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/user/create-guest`,undefined,options
    );
  }

export const userControllerGetUserLimit = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/user/getUserLimit`,options
    );
  }

export const userControllerGetUserByEmail = <TData = AxiosResponse<void>>(
    email: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/user/getUserByEmail/email/${email}`,options
    );
  }

export const userControllerDeactiveUser = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/user/deactiveUser`,undefined,options
    );
  }

export const userControllerGetProfile = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/user/getProfileMe`,options
    );
  }

export const userControllerSearchUser = <TData = AxiosResponse<void>>(
    params?: UserControllerSearchUserParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/user`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const userControllerUpdateProfile = <TData = AxiosResponse<void>>(
    updateProfileDTO: UpdateProfileDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:3000/user/updateProfile`,
      updateProfileDTO,options
    );
  }

export const vehicleControllerCreateVehicle = <TData = AxiosResponse<void>>(
    createVehicleDTO: CreateVehicleDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/vehicle/create`,
      createVehicleDTO,options
    );
  }

export const vehicleControllerGetVehicleById = <TData = AxiosResponse<Vehicle>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/vehicle/${id}`,options
    );
  }

export const vehicleControllerDeleteVehicle = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3000/vehicle/${id}`,options
    );
  }

export const vehicleControllerGetVehicles = <TData = AxiosResponse<void>>(
    params?: VehicleControllerGetVehiclesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/vehicle`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const routeControllerCreateRoute = <TData = AxiosResponse<void>>(
    createRouteDTO: CreateRouteDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/route/create`,
      createRouteDTO,options
    );
  }

export const routeControllerGetRoutes = <TData = AxiosResponse<void>>(
    params?: RouteControllerGetRoutesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/route/list`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const routeControllerDeleteRoute = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3000/route/${id}`,options
    );
  }

export const locationControllerCreateLocation = <TData = AxiosResponse<void>>(
    createLocationDto: CreateLocationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/location`,
      createLocationDto,options
    );
  }

export const locationControllerDeleteLocationDto = <TData = AxiosResponse<void>>(
    deleteLocationDto: DeleteLocationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3000/location`,{data:
      deleteLocationDto, ...options}
    );
  }

export const locationControllerGetAllLocation = <TData = AxiosResponse<CreateLocationDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/location/get-all`,options
    );
  }

export const locationControllerGetLocationDetail = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/location/get-location-detail`,options
    );
  }

export const stopPointControllerGetStopPoints = <TData = AxiosResponse<void>>(
    params?: StopPointControllerGetStopPointsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/stop-point`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const stopPointControllerCreate = <TData = AxiosResponse<void>>(
    createStopPointDto: CreateStopPointDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/stop-point`,
      createStopPointDto,options
    );
  }

export const stopPointControllerUpdateStopPoint = <TData = AxiosResponse<void>>(
    updateStopPointDto: UpdateStopPointDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:3000/stop-point`,
      updateStopPointDto,options
    );
  }

export const stopPointControllerDeleteStopPoint = <TData = AxiosResponse<void>>(
    stopPointId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3000/stop-point/${stopPointId}`,options
    );
  }

export const stopPointControllerGetStopPointsByRoute = <TData = AxiosResponse<void>>(
    routeId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/stop-point/by-route/${routeId}`,options
    );
  }

export const tripControllerCreateTrip = <TData = AxiosResponse<void>>(
    createTripDTO: CreateTripDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/trip/create`,
      createTripDTO,options
    );
  }

export const tripControllerSearchTrip = <TData = AxiosResponse<void>>(
    params: TripControllerSearchTripParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/trip/search-trip`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tripControllerGetTripsByVehicle = <TData = AxiosResponse<void>>(
    params?: TripControllerGetTripsByVehicleParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/trip/vehicle`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tripControllerGenTrips = <TData = AxiosResponse<void>>(
    genTripDTO: GenTripDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/trip/gen-trips`,
      genTripDTO,options
    );
  }

export const tripControllerDeleteTrips = <TData = AxiosResponse<void>>(
    deleteTripDTO: DeleteTripDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3000/trip`,{data:
      deleteTripDTO, ...options}
    );
  }

export const tripControllerDeleteTripsBeforeDate = <TData = AxiosResponse<void>>(
    deleteTripBeforeDate: DeleteTripBeforeDate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3000/trip/delete-trips-before-date`,{data:
      deleteTripBeforeDate, ...options}
    );
  }

export const seatControllerGetSeatIsBookedByTripId = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/seat/get-seat-is-booked-by-trip-id`,options
    );
  }

export const ticketControllerCreateTicket = <TData = AxiosResponse<void>>(
    createTIcketDTO: CreateTIcketDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/ticket`,
      createTIcketDTO,options
    );
  }

export const ticketControllerUpdateTicket = <TData = AxiosResponse<void>>(
    updateTicketDTO: UpdateTicketDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:3000/ticket`,
      updateTicketDTO,options
    );
  }

export const ticketControllerSearchTicket = <TData = AxiosResponse<void>>(
    searchTicketDTO: SearchTicketDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/ticket/search`,
      searchTicketDTO,options
    );
  }

export const ticketControllerGetPaymentHistoryTicket = <TData = AxiosResponse<void>>(
    params?: TicketControllerGetPaymentHistoryTicketParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/ticket/payment-history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const ticketControllerGetMyTicket = <TData = AxiosResponse<void>>(
    params?: TicketControllerGetMyTicketParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/ticket/my-ticket`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const ticketControllerCancleTicket = <TData = AxiosResponse<void>>(
    cancleTicketDTO: CancleTicketDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:3000/ticket/cancle-ticket`,
      cancleTicketDTO,options
    );
  }

export const ticketControllerConfirmCancleTicket = <TData = AxiosResponse<void>>(
    confirmCancleTicketDTO: ConfirmCancleTicketDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/ticket/confirm-cancle`,
      confirmCancleTicketDTO,options
    );
  }

export const ticketControllerDeleteTicket = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3000/ticket/${id}`,options
    );
  }

export const ticketControllerFilterTicket = <TData = AxiosResponse<void>>(
    filterTicketDTO: FilterTicketDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/ticket/filter-ticket`,
      filterTicketDTO,options
    );
  }

export const ticketControllerGetTicketsByTrip = <TData = AxiosResponse<void>>(
    tripId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/ticket/by-trip/${tripId}`,options
    );
  }

export const ticketControllerFindTicketByPhone = <TData = AxiosResponse<void>>(
    phone: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/ticket/by-phone/${phone}`,options
    );
  }

export const refundRequestControllerSearchRefundRequest = <TData = AxiosResponse<void>>(
    searchRefundRequestDTO: SearchRefundRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/refund-request/search`,
      searchRefundRequestDTO,options
    );
  }

export const refundRequestControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateCancellationRequestDto: UpdateCancellationRequestDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://localhost:3000/refund-request/${id}`,
      updateCancellationRequestDto,options
    );
  }

export const vnpayControllerCreatePaymentUrl = <TData = AxiosResponse<void>>(
    createPaymentDto: CreatePaymentDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3000/vnpay/create-payment-url`,
      createPaymentDto,options
    );
  }

export const vnpayControllerVnpayCallback = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/vnpay/callback`,options
    );
  }

export const busCompanyRequestControllerCreate = <TData = AxiosResponse<void>>(
    busCompanyRequestControllerCreateBody: BusCompanyRequestControllerCreateBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append(`companyName`, createRequestDTO.companyName);
formData.append(`address`, createRequestDTO.address);
formData.append(`phoneNumber`, createRequestDTO.phoneNumber);
formData.append(`email`, createRequestDTO.email);
formData.append(`representativeName`, createRequestDTO.representativeName);
formData.append(`licenseNumber`, createRequestDTO.licenseNumber);
if(createRequestDTO.licenseFile !== undefined) {
 formData.append(`licenseFile`, createRequestDTO.licenseFile);
 }

    return axios.post(
      `http://localhost:3000/bus-company-requests`,
      formData,options
    );
  }

export const busCompanyRequestControllerGetList = <TData = AxiosResponse<void>>(
    params?: BusCompanyRequestControllerGetListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3000/bus-company-requests`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const busCompanyRequestControllerUpdate = <TData = AxiosResponse<void>>(
    updateBusCompanyRequestDTO: UpdateBusCompanyRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://localhost:3000/bus-company-requests`,
      updateBusCompanyRequestDTO,options
    );
  }

export type AuthControllerSendOtpRegisterResult = AxiosResponse<void>
export type AuthControllerRegisterResult = AxiosResponse<void>
export type AuthControllerRegisterProviderResult = AxiosResponse<void>
export type AuthControllerLoginResult = AxiosResponse<void>
export type AuthControllerLogoutResult = AxiosResponse<void>
export type AuthControllerSendOtpResult = AxiosResponse<void>
export type AuthControllerVerifyOtpResult = AxiosResponse<void>
export type AuthControllerSendReserPasswordLinkResult = AxiosResponse<void>
export type AuthControllerResetPasswordResult = AxiosResponse<void>
export type AuthControllerChangePasswordResult = AxiosResponse<void>
export type AuthControllerGoogleAuthResult = AxiosResponse<void>
export type AuthControllerGoogleAuthCallbackResult = AxiosResponse<void>
export type UserControllerCreateGuestResult = AxiosResponse<void>
export type UserControllerGetUserLimitResult = AxiosResponse<void>
export type UserControllerGetUserByEmailResult = AxiosResponse<void>
export type UserControllerDeactiveUserResult = AxiosResponse<void>
export type UserControllerGetProfileResult = AxiosResponse<void>
export type UserControllerSearchUserResult = AxiosResponse<void>
export type UserControllerUpdateProfileResult = AxiosResponse<void>
export type VehicleControllerCreateVehicleResult = AxiosResponse<void>
export type VehicleControllerGetVehicleByIdResult = AxiosResponse<Vehicle>
export type VehicleControllerDeleteVehicleResult = AxiosResponse<void>
export type VehicleControllerGetVehiclesResult = AxiosResponse<void>
export type RouteControllerCreateRouteResult = AxiosResponse<void>
export type RouteControllerGetRoutesResult = AxiosResponse<void>
export type RouteControllerDeleteRouteResult = AxiosResponse<void>
export type LocationControllerCreateLocationResult = AxiosResponse<void>
export type LocationControllerDeleteLocationDtoResult = AxiosResponse<void>
export type LocationControllerGetAllLocationResult = AxiosResponse<CreateLocationDto[]>
export type LocationControllerGetLocationDetailResult = AxiosResponse<void>
export type StopPointControllerGetStopPointsResult = AxiosResponse<void>
export type StopPointControllerCreateResult = AxiosResponse<void>
export type StopPointControllerUpdateStopPointResult = AxiosResponse<void>
export type StopPointControllerDeleteStopPointResult = AxiosResponse<void>
export type StopPointControllerGetStopPointsByRouteResult = AxiosResponse<void>
export type TripControllerCreateTripResult = AxiosResponse<void>
export type TripControllerSearchTripResult = AxiosResponse<void>
export type TripControllerGetTripsByVehicleResult = AxiosResponse<void>
export type TripControllerGenTripsResult = AxiosResponse<void>
export type TripControllerDeleteTripsResult = AxiosResponse<void>
export type TripControllerDeleteTripsBeforeDateResult = AxiosResponse<void>
export type SeatControllerGetSeatIsBookedByTripIdResult = AxiosResponse<void>
export type TicketControllerCreateTicketResult = AxiosResponse<void>
export type TicketControllerUpdateTicketResult = AxiosResponse<void>
export type TicketControllerSearchTicketResult = AxiosResponse<void>
export type TicketControllerGetPaymentHistoryTicketResult = AxiosResponse<void>
export type TicketControllerGetMyTicketResult = AxiosResponse<void>
export type TicketControllerCancleTicketResult = AxiosResponse<void>
export type TicketControllerConfirmCancleTicketResult = AxiosResponse<void>
export type TicketControllerDeleteTicketResult = AxiosResponse<void>
export type TicketControllerFilterTicketResult = AxiosResponse<void>
export type TicketControllerGetTicketsByTripResult = AxiosResponse<void>
export type TicketControllerFindTicketByPhoneResult = AxiosResponse<void>
export type RefundRequestControllerSearchRefundRequestResult = AxiosResponse<void>
export type RefundRequestControllerUpdateResult = AxiosResponse<void>
export type VnpayControllerCreatePaymentUrlResult = AxiosResponse<void>
export type VnpayControllerVnpayCallbackResult = AxiosResponse<void>
export type BusCompanyRequestControllerCreateResult = AxiosResponse<void>
export type BusCompanyRequestControllerGetListResult = AxiosResponse<void>
export type BusCompanyRequestControllerUpdateResult = AxiosResponse<void>
