"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderWrapper from "@/component/layout/HeadreWrapper";
import { Toaster } from "sonner";
import ReduxProvider from "@/redux/provider";
import UserInitialize from "@/component/layout/UserInitialize";
import SearchBar from "../component/layout/SearchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <UserInitialize />
          {/* <PageLoading /> */}
          <Toaster
            position="top-right"
            duration={3000}
            richColors
            closeButton
          />
          <HeaderWrapper />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
